### PR TITLE
Basic example of application packaging

### PR DESCRIPTION
**Pull request by sv3ndk**
Hi, 

I added a basic example of a scala application that wraps `WordCount`.

I also provided instructions in the README regarding how to launch that application directly from `sbt` as well as how to package it as a "fat-jar" that can be sent to a spark master through `spark-submit`. 

In the process I removed the dependency towards spark through the `sbt-spark-package` and replaced them by explicit dependencies as `libraryDependencies`. This allows me to mark the jars as `provided` so they are not included in the fat-jar. I think there is more control that way, especially if exclusion rules start to be necessary for the packaging. 

I hope you find that interesting :) 

Any feed-back welcome, 

Svend

### CODE REVIEW

**Review by holdenk — COMMENTED** [review]
So what's the reasoning behind getting rid of the spark-packages plugin?

**Comment by sv3ndk** [comment]
Hmm, maybe I got that wrong. 

I figured the only reason it was used so far was to declare the dependencies towards spark mllib, core... so since those have been replaced with explicit dependencies within `libraryDependencies`, the plug-in would no longer be required? 

Would you rather keep the plugin declared in `project/plugin.sbt`, so it's easier to use when it becomes needed again?

**Comment by holdenk** [comment]
It's also useful for packaging spark packages and including other spark-packages.

**Comment by sv3ndk** [comment]
I see. I'll put it back then.

**Pull request merged**
